package metrics

import (
	"context"
	"fmt"
	"github.com/Jeffail/gabs/v2"
	"net/http"
	"strconv"
	"sync"
	"time"
)

// open container is open for modification with SetProperty, AddCount, and IncrementCount.
// closed container is set by Emit or
type Metrics struct {
	open      *gabs.Container
	closed    *gabs.Container
	counters  map[string]int64
	floaters  map[string]float64
	timings   map[string]*TimingStats
	mu        sync.Mutex
	startTime time.Time
}

// Default counter metrics that are always emitted.
const (
	CounterKeyFault    = "fault"
	CounterKeyPanicked = "panicked"
)

// Reserved property keys.
const (
	ReservedKeyStartTime = "startTime"
	ReservedKeyEndTime   = "endTime"
	ReservedKeyTime      = "time"
	ReservedKeyCounters  = "counters"
	ReservedKeyFloaters  = "floaters"
	ReservedKeyTimings   = "timings"
)

// For Metrics.SetProperty.
var reservedKeys = map[string]bool{
	ReservedKeyCounters:  true,
	ReservedKeyFloaters:  true,
	ReservedKeyEndTime:   true,
	ReservedKeyStartTime: true,
	ReservedKeyTime:      true,
	ReservedKeyTimings:   true,
}

// Creates an empty Metrics instance. The current UTC time will be the startTime property.
func New() *Metrics {
	return NewWithStartTime(time.Now())
}

// A variant of New that allows caller to override the startTime property.
func NewWithStartTime(startTime time.Time) *Metrics {
	return &Metrics{
		open: gabs.New(),
		counters: map[string]int64{
			CounterKeyFault:    0,
			CounterKeyPanicked: 0,
		},
		floaters:  map[string]float64{},
		timings:   map[string]*TimingStats{},
		mu:        sync.Mutex{},
		startTime: startTime.UTC(),
	}
}

// Convenient method that panics if err is not nil.
func Must(m *Metrics, err error) *Metrics {
	if err != nil {
		panic(err)
	}
	return m
}

// Creates a Metrics instance with the specified properties.
func NewWithProperties(properties map[string]interface{}) (*Metrics, error) {
	startTime := time.Now().UTC()

	container := gabs.New()
	for k, v := range properties {
		if v == nil {
			continue
		}

		if _, err := container.Set(v, k); err != nil {
			return nil, err
		}
	}

	return &Metrics{
		open:      container,
		mu:        sync.Mutex{},
		startTime: startTime,
	}, nil
}

// Sets a property to be logged. A few keys are generated by the metrics instance and cannot be overridden, and thus
// will be ignored by this method: startTime, endTime, time, timings, and counters.
func (m *Metrics) SetProperty(key string, v interface{}) error {
	if v == nil || reservedKeys[key] {
		return nil
	}

	if err := m.checkLock(); err != nil {
		return err
	}
	defer m.mu.Unlock()

	if _, err := m.open.Set(v, key); err != nil {
		return err
	}

	return nil
}

// A panicky fluent variant of SetProperty.
func (m *Metrics) MustSetProperty(key string, v interface{}) *Metrics {
	if err := m.SetProperty(key, v); err != nil {
		panic(err)
	}
	return m
}

// Increases the counter of the specified key by some delta.
func (m *Metrics) AddCount(key string, delta int64) error {
	if err := m.checkLock(); err != nil {
		return err
	}
	defer m.mu.Unlock()

	m.counters[key] += delta
	return nil
}

// A panicky fluent variant of AddCount.
func (m *Metrics) MustAddCount(key string, delta int64) *Metrics {
	if err := m.AddCount(key, delta); err != nil {
		panic(err)
	}
	return m
}

// Increments the counter of the specified key by 1.
func (m *Metrics) IncrementCount(key string) error {
	if err := m.checkLock(); err != nil {
		return err
	}
	defer m.mu.Unlock()

	m.counters[key]++
	return nil
}

// A panicky fluent variant of func (m *Metrics) IncrementCount(key string) error {.
func (m *Metrics) MustIncrementCount(key string) *Metrics {
	if err := m.IncrementCount(key); err != nil {
		panic(err)
	}
	return m
}

// Increases the float counter of the specified key by some delta.
func (m *Metrics) AddFloat(key string, delta float64) error {
	if err := m.checkLock(); err != nil {
		return err
	}
	defer m.mu.Unlock()

	m.floaters[key] += delta
	return nil
}

// A panicky fluent variant of AddFloat.
func (m *Metrics) MustAddFloat(key string, delta float64) *Metrics {
	if err := m.AddFloat(key, delta); err != nil {
		panic(err)
	}
	return m
}

// Add a timing metric.
func (m *Metrics) AddTiming(key string, duration time.Duration) error {
	if err := m.checkLock(); err != nil {
		return err
	}
	defer m.mu.Unlock()

	stats, ok := m.timings[key]
	if !ok {
		stats = NewTimingStats(duration)
		m.timings[key] = stats
		return nil
	}

	stats.Add(duration)
	return nil
}

// Add a timing metric.
func (m *Metrics) MustAddTiming(key string, duration time.Duration) *Metrics {
	if err := m.AddTiming(key, duration); err != nil {
		panic(err)
	}
	return m
}

// Increments the counter of CounterKeyFault by 1.
func (m *Metrics) Faulted() error {
	if err := m.checkLock(); err != nil {
		return err
	}
	defer m.mu.Unlock()

	m.counters[CounterKeyFault]++
	return nil
}

// Increments the counter of CounterKeyPanicked by 1.
func (m *Metrics) Panicked() error {
	if err := m.checkLock(); err != nil {
		return err
	}
	defer m.mu.Unlock()

	m.counters[CounterKeyPanicked]++
	return nil
}

// Returns a non-nil error if the Metrics instance is closed for modification.
func (m *Metrics) checkLock() error {
	m.mu.Lock()

	if m.closed != nil {
		return fmt.Errorf("metrics instance already closed")
	}
	return nil
}

// Closes the Metrics instance for modification.
// Sets endTime to the current UTC time which will be used in conjunction with startTime to compute the time property.
// Subsequent modifications to the Metrics instance will result in an error.
// Subsequent calls to Close will have no effect.
func (m *Metrics) Close() {
	m.CloseWithEndTime(time.Now().UTC())
}

// A variant of Close that allows caller to override the endTime property.
func (m *Metrics) CloseWithEndTime(endTime time.Time) {
	if m.closed != nil {
		return
	}

	m.mu.Lock()
	defer m.mu.Unlock()

	if m.closed != nil {
		return
	}

	c := gabs.New()
	_ = c.Merge(m.open)
	_, _ = c.Set(m.startTime.UnixNano()/int64(time.Millisecond), ReservedKeyStartTime)
	_, _ = c.Set(endTime.Format(http.TimeFormat), ReservedKeyEndTime)
	_, _ = c.Set(formatDuration(endTime.Sub(m.startTime)), ReservedKeyTime)

	if len(m.counters) != 0 {
		_, _ = c.Set(m.counters, ReservedKeyCounters)
	}

	if len(m.floaters) != 0 {
		_, _ = c.Set(m.floaters, ReservedKeyFloaters)
	}

	if len(m.timings) != 0 {
		for k, timing := range m.timings {
			o, err := c.Object(ReservedKeyTimings, k)
			if err != nil {
				continue
			}
			_, _ = o.Set(formatDuration(timing.Sum), "sum")
			_, _ = o.Set(formatDuration(timing.Min), "min")
			_, _ = o.Set(formatDuration(timing.Max), "max")
			_, _ = o.Set(timing.N, "n")
			_, _ = o.Set(formatDuration(timing.Sum/time.Duration(timing.N)), "avg")
		}
	}

	m.closed = c
}

// Returns whether the Metrics instance is closed for modification.
func (m *Metrics) IsClosed() bool {
	return m.closed != nil
}

// Closes the Metrics instance and emits the JSON string describing the instance.
// Subsequent calls will return the same JSON string.
func (m *Metrics) JSONString() string {
	m.Close()
	return m.closed.String()
}

// A variant of EmitJSON with indentation.
func (m *Metrics) JSONStringIndent(prefix string, indent string) string {
	m.Close()
	return m.closed.StringIndent(prefix, indent)
}

type key int

var metricsKey key

// Returns a new Context that carries the specified Metrics instance.
func NewContext(ctx context.Context, metrics *Metrics) context.Context {
	newCtx := context.WithValue(ctx, metricsKey, metrics)
	return newCtx
}

// Returns the Metrics value stored in context, if any.
func FromContext(ctx context.Context) (*Metrics, bool) {
	m, ok := ctx.Value(metricsKey).(*Metrics)
	return m, ok
}

// A panicky variant of FromContext.
func MustFromContext(ctx context.Context) *Metrics {
	m, ok := FromContext(ctx)
	if !ok {
		panic("no metrics context")
	}
	return m
}

func formatDuration(duration time.Duration) string {
	return strconv.FormatFloat(float64(duration.Nanoseconds())/float64(time.Millisecond), 'f', 3, 64) + " ms"
}
